all:
  children:
    management:
      hosts:
        mgmt-server:
          ansible_host: 192.168.100.10
          ansible_user: root
          ansible_ssh_pass: dksgo1234
          
    sdn_controllers:
      hosts:
        sdn-controller:
          ansible_host: 192.168.100.20
          ansible_user: root
          ansible_ssh_pass: dksgo1234
          
    app_servers:
      hosts:
        app-server1:
          ansible_host: 192.168.100.30
          ansible_user: root
          ansible_ssh_pass: dksgo1234

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
